Merge master into PatrikLundell/47 (INCOMPLETE) (#400)
Conflicts:
    df.art.xml
    df.entities.xml (not yet resolved)
    df.history.xml
    df.military.xml
    df.world-site.xml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,15 +15,16 @@ jobs:
             libxml-libxslt-perl
     - name: Clone df-structures
       uses: actions/checkout@v1
-      with:
-        submodules: true
     - name: Validate against schema
       run: |
-        xmllint --schema data-definition.xsd --noout df.*.xml symbols.xml
+        xmllint --schema data-definition.xsd --noout df.*.xml symbols.xml 2>&1 | tee xmllint.out; status=${PIPESTATUS[0]}
+        echo "** reformatted output: **"
+        grep -i error xmllint.out | perl -pe 's/(.+):(\d+):/::error file=\1,line=\2::/g'
+        exit $status
     - name: Generate headers
       run: |
-        perl ./codegen.pl | tee codegen-out.txt
-        if grep -i error codegen-out.txt; then
+        perl ./codegen.pl | tee codegen.out
+        if grep -i error codegen.out; then
           echo codegen produced error
           exit 1
         fi
